package com.tcc.Login;

import com.tcc.ConexaoBD.ConexaoDB;
import com.tcc.principal.Principal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @authopor 
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form SemAcao
     */
    public FormLogin() {

        initComponents();

    }
    
/**
 * Metodo responsavel em buscar na tabela tbusuarios do BD,
 * informações de acesso ao sistema.
 */
    public void logar() {

        // instanciando objetos necessarios para fazer a conexao
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        //String sql de coleta de dados
        String sql = "select*from baseEstoque.tbusuarios where login=? and senha=?";
        
        // este atributo ira armazenar o perfil do usuario que esta gravado no BD
        String per;
        
        try {
            
            // abrindo a conexao com o BD.
            Connection conexao = ConexaoDB.getconection();
            pst = conexao.prepareStatement(sql);
            
            // As linhas abaixo pega os valores dos campos de usuario e senha
            // e atribui ao login e senha da linha sql
            pst.setString(1, campoUsuario.getText());
            pst.setString(2, campoSenha.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                //obtendo o conteudo da coluna perfil, que na posicao 5 no BD;
                per = rs.getString(5);
                //System.out.println(per);
                
                if (per.equals("Admin")) {
                    
                    Principal telaPrincipal = new Principal();
                    telaPrincipal.setVisible(true); 
                    
                    // aqui alteramos o texto da label que fica no rodapé da tela principal
                    // colocando o nome do usuario logado.
                    Principal.lblUsuario.setText(rs.getString(2));

                    // fechando a tela principal.
                    this.dispose();
                    
                } else {
                    
                    Principal telaPrincipal = new Principal();
                    telaPrincipal.setVisible(true);
                    Principal.lblUsuario.setText(rs.getString(2));
                    this.dispose();
//                  JOptionPane.showMessageDialog(null, "erro nao abriu");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario ou senha invalida!");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar ler tabela Usuarios\n " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faça seu login");
        setBackground(new java.awt.Color(247, 247, 247));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        jPanel1.add(campoUsuario);
        campoUsuario.setBounds(140, 40, 210, 30);

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 50, 94, 19);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 100, 94, 19);

        campoSenha.setCaretColor(new java.awt.Color(204, 0, 51));
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(campoSenha);
        campoSenha.setBounds(140, 90, 210, 30);

        btnConfirmar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnConfirmar.setText("ENTRAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(60, 160, 120, 30);

        btnLimpar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(200, 160, 109, 30);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(320, 160, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 270);

        setSize(new java.awt.Dimension(458, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        logar();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        campoSenha.setText(""); //limpa o campo de senha
        campoUsuario.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed

    }//GEN-LAST:event_campoSenhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnConfirmar;
    javax.swing.JButton btnLimpar;
    javax.swing.JButton btnSair;
    javax.swing.JPasswordField campoSenha;
    javax.swing.JTextField campoUsuario;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
